### ISSUE TITLE
Pass in comment or other field values as url parameters

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContactForm#11]
We often need to add really simple feedback mechanisms to pages, e.g. mailto: links with subject line generated to include something about the page, like a record ID. 

Mailto links are obviously terrible for spam, so it wold be much nicer to use the contact form (with recaptcha). But the contact form has no context-awareness. 

This could become a useful mechanism if we could make links to the contact form with URL parameters e.g.

<a href="/contact?c=feedback+on+record+mxg12345">Give us your feedback on this record</a>

and on loading the /contact page the text from the url parameter becomes the default content of the "Comment" control, which the user then augments.

By extension, this could also work for the 12 other optional fields that can be enabled, with some convention for the parameter naming.

**Comment by joeaudette** [comment]
This kind of custom logic can be easily accomplished by overriding the view in your project and adding the needed logic directly in the view. You have access to the request, query string params and the model there. To use the extra custom optional fields you would need to override the view anyway.

I don't think any change is needed in SimpleContactForm code to support that kind of thing.

I would be careful though about trusting query string parameters without checking them for expected values. Razor views by default would html encode any values so not so much security issue but someone could craft an url with offensive messages and send it to a user in html email for example if you just let in anything.

**Comment by CrispinF** [comment]
Good point - I hadn't thought of that. Thanks for the tip.
