### ISSUE TITLE
Bug Report - Recapture Settings not getting picked up from the Administration Capture Settings UI

### ISSUE THREAD

**Issue by hsankala** [cloudscribe/cloudscribe.SimpleContactForm#15]
Hi Joe.  I set my google recapture keys in the UI of cloudscribe administration, but the contact form didn't pickup the changes.

![image](https://user-images.githubusercontent.com/14014749/56131207-c230b200-5f7e-11e9-951e-fc912b5f4d80.png)

But I did see a 'I am not a robot' checkbox under the comment form.

I set the same settings in appsettings.json and the contact and login forms picked it up fine

**Comment by joeaudette** [comment]
Hi Hefin,

I think the bug is in our project template.

These lines:

            services.AddCloudscribeSimpleContactFormCoreIntegration(config);
            services.AddCloudscribeSimpleContactForm(config);

should come after this line:

    services.AddCloudscribeCoreMvc(config);

so that the cloudscribe core recaptcha keys resolver gets injected first before contact form is added. In the template the first line is also missing.

I will fix that asap.

**Comment by joeaudette** [comment]
@hsankala I've just published updated project templates but you should be able to solve it in your existing project by making the changes mentioned.

**Comment by hsankala** [comment]
Cheers Joe. Will do.
